[package]
name = "seratodj"
version = "0.1.0"
authors = ["Jan Holthuis <jan.holthuis@ruhr-uni-bochum.de>"]
description = "A library for parsing Serato DJ's metadata and database."
readme = "README.md"
repository = "https://github.com/Holzhaus/seratodj-rs"
license = "AGPL-3.0-or-later"
keywords = [
    "serato", "dj", "tag", "metadata", "id3", "geob", "flac", "ogg", "mp4",
    "library", "database", "parser"
]
categories = ["parser-implementations"]
edition = "2018"

[dependencies]
nom = "6.1.0"
base64 = "0.13.0"
thiserror = "1.0"

[dev-dependencies]
id3 = "0.5.1"
textwrap = "0.13.2"
