[package]
name = "serato-tags"
version = "0.1.0"
authors = ["Jan Holthuis <jan.holthuis@ruhr-uni-bochum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
id3 = "0.5.1"
