[package]
name = "triseratops"
version = "0.0.1"
authors = ["Jan Holthuis <jan.holthuis@ruhr-uni-bochum.de>"]
description = "The robust, in-depth Serato Parser & Serializer."
readme = "README.md"
repository = "https://github.com/Holzhaus/triseratops"
license = "AGPL-3.0-or-later"
keywords = ["serato", "dj", "tag", "database", "parser"]
categories = ["parser-implementations"]
edition = "2018"

[dependencies]
nom = "6.1.0"
base64 = "0.13.0"
thiserror = "1.0"

[dev-dependencies]
id3 = "0.5.1"
textwrap = "0.13.2"
